version: '2'
services:
  db:
    image: postgres
    env_file: ./.db.env
  web:
    build: .
    command: bash -c "sleep 3 && bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: ./.db.env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
